image: alpine/edge
secrets:
  - af3888de-0580-42e3-86a8-69d9d97b70cf
sources:
  - https://git.sr.ht/~rolandog/pam-u2f-totp-config
tasks:
  - fetch-and-validate-github-key-fingerprint: |
      ssh-keyscan -t rsa github.com > github_host
      ssh-keygen -lf github_host > github_fingerprint
      grep -R "nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8" github_fingerprint
  - mirror-to-github: |
      echo -e "Host github.com\n    IdentityFile ~/.ssh/id_rsa\n    IdentitiesOnly yes\n    BatchMode yes\n" >> ~/.ssh/config
      cat github_host >> ~/.ssh/known_hosts
      cd ~/pam-u2f-totp-config
      git remote add github git@github.com:rolandog/pam-u2f-totp-config.git
      git push --prune github +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/* main

